version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: diglit
      POSTGRES_USER: diglit
      POSTGRES_PASSWORD: diglit
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  api:
    build:
      context: ./modules/backend
      dockerfile: Dockerfile.dev
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgresql://diglit:diglit@postgres:5432/diglit
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./modules/backend:/app
      - /app/__pycache__

volumes:
  postgres_data:
