name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.17.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Check dev env
        run: npm run dev:env

      - name: Typecheck web
        run: npm run typecheck

      - name: Build web
        run: npm run build

      - name: Upload artifact (web)
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: .scripts/modules/frontend/apps/web/diglit-web/dist
